[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
foldhash = { version = "0.1.4", default-features = false }
hashbrown = "0.15.2"

[dev-dependencies]
eframe = "0.31.1"
rand = "0.9.0"
ratatui = "0.29.0"
